name: search3
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image: ^4.1.3
  image_picker: ^1.0.4
  tflite_flutter: ^0.10.2
  camera: ^0.10.5+5
  injector: ^3.0.0
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/labels.txt
    - assets/models/labels_ru.txt
    - assets/models/mobilenet_quant.tflite
    - assets/images/auth_test.png
    - assets/images/auth_background.jpg

  fonts:
    - family: Magic
      fonts:
      - asset: assets/fonts/YuseiMagic-Regular.ttf
